#!/bin/bash

function show_help() {
    sname=`basename $0`
    cat <<- EOF
$sname -f<CSV filename> [-hnr] [-s <sep>] [-c <col>]

$sname sorts a CSV on a column specified by the numeric argument to the -c
flag. The default separator "," can be changed by passing an alternative
character as an argument to the -s flag. -n flag sorts numerically, -r sorts
in descending order and -h flag shows this help.

Author: Amey Joshi
Version: 1.0
Date: 20Sep2023
EOF
}

function show_results() {
    fname=$1
    sep=$2
    col=$3
    numeric=$4
    reverse=$5
    pretty_print=$6

    tmpfile_1=$(mktemp)
    cat $fname | sed 1d > $tmpfile_1

    cmd="sort $tmpfile_1 -k$col -t'$sep'"

    if [ $numeric -eq 1 ]; then
        cmd=$cmd" -n"
    fi

    if [ $reverse -eq 1 ]; then
        cmd=$cmd" -r"
    fi

    if [ $pretty_print -eq 1 ]; then
        tmpfile_2=$(mktemp)
        head -1 $fname > $tmpfile_2
        cmd=$cmd" >> $tmpfile_2"
        eval "$cmd"
        column -s$sep -t $tmpfile_2
        rm $tmpfile_2
    else
        head -1 $fname
        eval "$cmd"
    fi

    rm $tmpfile_1
}

fname=""
sep=","
col=1
numeric=0
reverse=0
pretty_print=0
hflag=0

while getopts ':f:h:s:c:nrp' opt; do
    case "$opt" in
        f) fname=$OPTARG
        ;;
        s) sep=$OPTARG
        ;;
        c) col=$OPTARG
        ;;
        n) numeric=1
        ;;
        r) reverse=1
        ;;
        p) pretty_print=1
        ;;
        h) hflag=1
        ;;
        *) hflag=1
        ;;
    esac
done

if [ $hflag -eq 1 ]; then
    show_help
    exit 0
fi
 
if [ -z $fname ]; then
    echo "No file specified"
    show_help
else
    show_results $fname $sep $col $numeric $reverse $pretty_print
fi

