[package]
name = "collections"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.5"

[[bin]]
name = "vectors"
path = "src/vectors.rs"

[[bin]]
name = "pig_latin"
path = "src/pig_latin.rs"
